import type { Metadata } from "next";
import { Fredoka, Nunito, Inter, Quicksand } from "next/font/google";
import "./globals.css";
import 'bootstrap-icons/font/bootstrap-icons.css';

const fredoka = Fredoka({
  variable: "--font-logo",
  subsets: ["latin"],
});

const nunito = Nunito({
  variable: "--font-titulo",
  subsets: ["latin"],
});
const inter = Inter({
  variable: "--font-subtitulo",
  subsets: ["latin"],
});
const quicksand = Quicksand({
  variable: "--font-texto",
  subsets: ["latin"],
});
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${fredoka.variable} ${nunito.variable} ${inter.variable} ${quicksand.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
